import type { Plan } from "./PlanCard";

export const freeTrialPlan: Plan = {
  id: "trial",
  cardClass: "plan-card featured",
  badge: "Try Free",
  tagClass: "tag badge-green",
  tagLabel: "Free Trial",
  price: "£0",
  pricePeriod: "/7 days",
  priceNote: "No card required — start browsing today",
  desc: "Full Premium access for 7 days. Browse deals and prepare listing drafts.",
  features: [
    { included: true, text: "7 days of Premium browsing" },
    { included: true, text: "Full contact details revealed" },
    { included: true, text: "Complete deal analysis (Flip + BTL)" },
    { included: true, text: "Prepare listing drafts" },
    { included: false, text: "Publish listings (subscribe required)" },
    { included: true, text: "Upgrade to Premium anytime" },
  ],
  buttonClass: "btn btn-gold",
  buttonStyle: { width: "100%" },
  buttonLabel: "Start 7 Days Free Trial →",
};

export const plans: Plan[] = [
  {
    id: "premium",
    cardClass: "plan-card",
    badge: "Most Popular",
    tagClass: "tag badge-green",
    tagLabel: "Premium",
    price: "£35",
    priceNote: "for your first 3 months, then £49/mo",
    desc: "Full access to listings, analysis, and contact details.",
    features: [
      { included: true, text: "Unlimited deal browsing" },
      { included: true, text: "Full contact details revealed" },
      { included: true, text: "Complete deal analysis (Flip + BTL)" },
      { included: true, text: "Unlimited searches & filters" },
      { included: true, text: "Submit listings (£10 per listing)" },
      { included: true, text: "Save & favourite properties" },
    ],
    buttonClass: "btn btn-gold",
    buttonStyle: { width: "100%" },
    buttonLabel: "Subscribe Now →",
  },
  {
    id: "commercial",
    cardClass: "plan-card featured",
    badge: "Invite Only",
    tagClass: "tag badge-amber",
    tagLabel: "Founders Club",
    price: "£25",
    priceNote: "fixed for 12 months · Commercial Partnership",
    desc: "Exclusive invite-only terms: no listing fees and a 5% success fee on deals.",
    features: [
      { included: true, text: "£25/mo fixed for 12 months" },
      { included: true, text: "No property listing fees" },
      { included: true, text: "5% success fee on partner remuneration" },
      { included: true, text: "Full Premium browsing & analysis" },
      { included: true, text: "Publish listings without £10 fee" },
      { included: true, text: "Invite-only — not open to public" },
    ],
    buttonClass: "btn btn-gold",
    buttonStyle: { width: "100%" },
    buttonLabel: "Enter Invite Code →",
    inviteOnly: true,
  },
  {
    id: "vip",
    cardClass: "plan-card vip plan-card-coming-soon",
    tagClass: "tag",
    tagLabel: "VIP",
    price: "£79",
    desc: "The complete platform with exclusive off-market deals.",
    comingSoon: true,
    features: [
      { included: true, text: "Everything in Premium" },
      { included: true, text: "VIP-exclusive off-market deals" },
      { included: true, text: "Priority listing approval" },
      { included: true, text: "Dedicated account manager" },
      { included: true, text: "Advanced analytics dashboard" },
      { included: true, text: "Early access to new features" },
    ],
    buttonClass: "btn btn-gold",
    buttonStyle: { width: "100%", background: "var(--gold-lt)" },
    buttonLabel: "Coming Soon",
  },
  {
    id: "ultra",
    cardClass: "plan-card plan-card-coming-soon",
    tagClass: "tag",
    tagLabel: "Ultra",
    price: "£99",
    desc: "Our top tier for high-volume investors — details coming soon.",
    comingSoon: true,
    features: [
      { included: true, text: "Everything in VIP" },
      { included: true, text: "Highest priority support" },
      { included: true, text: "Bespoke deal sourcing" },
    ],
    buttonClass: "btn btn-outline",
    buttonStyle: { width: "100%" },
    buttonLabel: "Coming Soon",
  },
];
