import type { Plan } from "./PlanCard";

export const plans: Plan[] = [
  {
    id: "free",
    cardClass: "plan-card",
    tagClass: "tag badge-blue",
    tagLabel: "Free",
    price: "£0",
    desc: "Get started and browse limited deal information.",
    features: [
      { included: true, text: "Browse up to 10 deals/month" },
      { included: true, text: "See asking price & location" },
      { included: true, text: "Basic search filters" },
      { included: false, text: "Contact details" },
      { included: false, text: "Full deal analysis" },
      { included: false, text: "Unlimited searches" },
      { included: false, text: "Submit listings" },
      { included: false, text: "Email deal alerts" },
    ],
    buttonClass: "btn btn-outline",
    buttonStyle: { width: "100%" },
    buttonLabel: "Current Plan",
  },
  {
    id: "premium",
    cardClass: "plan-card featured",
    badge: "Most Popular",
    tagClass: "tag badge-green",
    tagLabel: "Premium",
    price: "£29",
    desc: "Full access to listings, analysis, and contact details.",
    features: [
      { included: true, text: "Unlimited deal browsing" },
      { included: true, text: "Full contact details revealed" },
      { included: true, text: "Complete deal analysis (Flip + BTL)" },
      { included: true, text: "Unlimited searches & filters" },
      { included: true, text: "Submit listings (up to 10/mo)" },
      { included: true, text: "Email deal alerts" },
      { included: true, text: "Save & favourite properties" },
      { included: false, text: "VIP-only exclusive deals" },
    ],
    buttonClass: "btn btn-gold",
    buttonStyle: { width: "100%" },
    buttonLabel: "Upgrade to Premium →",
  },
  {
    id: "vip",
    cardClass: "plan-card vip",
    tagClass: "tag",
    tagLabel: "VIP",
    price: "£79",
    desc: "The complete platform with exclusive off-market deals.",
    features: [
      { included: true, text: "Everything in Premium" },
      { included: true, text: "VIP-exclusive off-market deals" },
      { included: true, text: "Unlimited listing submissions" },
      { included: true, text: "Priority listing approval" },
      { included: true, text: "Dedicated account manager" },
      { included: true, text: "Advanced analytics dashboard" },
      { included: true, text: "Affiliate commission boost (+5%)" },
      { included: true, text: "Early access to new features" },
    ],
    buttonClass: "btn btn-gold",
    buttonStyle: { width: "100%", background: "var(--gold-lt)" },
    buttonLabel: "Upgrade to VIP →",
  },
];
