import type { Property } from "./PropertyCard";

export const properties: Property[] = [
  {
    id: "card-1",
    placeholder: "🏠",
    discount: "▼ 34%",
    featured: true,
    title: "3-Bed End Terrace, Manchester",
    location: "📍 Salford, Greater Manchester · M6",
    asking: "£118,000",
    market: "£178,000",
    saving: "£60,000",
    tags: [
      { label: "BTL", badge: "badge-green" },
      { label: "Flip", badge: "badge-blue" },
      { label: "🛏 3 bed" },
      { label: "🏚 House" },
    ],
    footerButtonLabel: "View Deal →",
    footerButtonClass: "btn btn-gold btn-sm",
    meta: "Added 2h ago · 12 saves",
  },
  {
    id: "card-2",
    placeholder: "🏢",
    discount: "▼ 41%",
    lock: { label: "Premium Required", buttonText: "Upgrade" },
    title: "Commercial Unit — Leeds City Centre",
    location: "📍 Leeds, West Yorkshire · LS1",
    asking: "£89,500",
    market: "£152,000",
    tags: [
      { label: "Commercial", badge: "badge-amber" },
      { label: "🏢 Office" },
    ],
    footerButtonLabel: "🔒 Unlock",
    footerButtonClass: "btn btn-outline btn-sm",
    meta: "Added 5h ago",
  },
  {
    id: "card-3",
    placeholder: "🏘",
    discount: "▼ 28%",
    title: "5-Bed HMO — Birmingham",
    location: "📍 Aston, Birmingham · B6",
    asking: "£195,000",
    market: "£270,000",
    saving: "£75,000",
    tags: [
      { label: "HMO", badge: "badge-green" },
      { label: "🛏 5 bed" },
      { label: "📊 9.2% yield" },
    ],
    footerButtonLabel: "View Deal →",
    footerButtonClass: "btn btn-gold btn-sm",
    meta: "Added 1d ago · 38 saves",
  },
  {
    id: "card-4",
    placeholder: "🏡",
    discount: "▼ 22%",
    title: "2-Bed Flat — Sheffield",
    location: "📍 Hillsborough, Sheffield · S6",
    asking: "£72,000",
    market: "£92,000",
    tags: [
      { label: "BTL", badge: "badge-blue" },
      { label: "🛏 2 bed" },
      { label: "🏢 Flat" },
    ],
    footerButtonLabel: "View Deal →",
    footerButtonClass: "btn btn-gold btn-sm",
    meta: "Added 2d ago",
  },
  {
    id: "card-5",
    placeholder: "🌿",
    discount: "▼ 35%",
    lock: { label: "VIP Required", buttonText: "Upgrade to VIP" },
    title: "Development Land — Nottingham",
    location: "📍 Beeston, Nottingham · NG9",
    asking: "£145,000",
    market: "£223,000",
    tags: [
      { label: "Land", badge: "badge-amber" },
      { label: "🏗 Dev. Opportunity" },
    ],
    footerButtonLabel: "🔒 VIP Only",
    footerButtonClass: "btn btn-outline btn-sm",
    meta: "Added 3d ago",
  },
  {
    id: "card-6",
    placeholder: "🏠",
    discount: "▼ 26%",
    featured: true,
    title: "4-Bed Detached — Liverpool",
    location: "📍 Walton, Liverpool · L4",
    asking: "£162,000",
    market: "£219,000",
    tags: [
      { label: "Flip", badge: "badge-blue" },
      { label: "BTL", badge: "badge-green" },
      { label: "🛏 4 bed" },
    ],
    footerButtonLabel: "View Deal →",
    footerButtonClass: "btn btn-gold btn-sm",
    meta: "Added 4d ago · 51 saves",
  },
];
